owner: kanarkco
repo: hold-status

sites:
  - name: Hold API
    url: https://hold.kanark.com/api/health
    expectedStatusCodes:
      - 200

status-website:
  baseUrl: /hold-status
  logoUrl: https://hold.kanark.com/logo.svg
  name: Hold Status
  introTitle: "**Hold** service status and uptime monitor"
  introMessage: Real-time status of Hold API services. Powered by [Upptime](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

notifications:
  - type: telegram
    botToken: $TELEGRAM_BOT_TOKEN
    chatId: $TELEGRAM_CHAT_ID
